### ISSUE TITLE
Rangeslider does not work on IOS

### ISSUE THREAD

**Issue by robwelan** [mnkhouri/react-circular-slider#8] opened 2020-07-08 22:55 UTC
If you use IOS safari / chrome etc, your documentation page does not work (not possible to drag the thumbs). It is essential that this product is cross browser compatible and mobile friendly. https://marc.khouri.ca/react-circular-slider/

**Comment by fireydude** [comment] 2022-09-21 10:40
this is a duplicate of #4

**Comment by mnkhouri** [comment] 2022-09-27 00:37
Closing as dupe of #4 , thanks @fireydude

**Closed as not planned by mnkhouri** 2022-09-27 00:37 UTC

**Comment by mnkhouri** [comment] 2022-10-16 06:03
Touch support published in v0.2.0!
